### ISSUE TITLE
Wrong color aproximation on terminal

### ISSUE THREAD

**Issue by ghost** [bkruczyk/badwolf-emacs#3]
This is really not a big issue, just for you to know it: there are subtle differences between the terminal version of vim and emacs.  The colors approximations of Emacs may differ from vim one.

![2016-01-15-222058_1366x768_scrot](https://cloud.githubusercontent.com/assets/7250745/12370163/48467538-bc07-11e5-8ffe-8ed0236627cb.png)

[Edit]: I actually altered the theme with an overlay theme that I enable on top of it, but there is no color name in it.  What I am referring to is the tint of the background and of the keywords that are different on emacs and vim terminals versions.

I use st (simpleterm).

**Comment by bkruczyk** [comment]
I'm using `#222120` for background and in Vim's theme it's `#1c1b1a`. 
I wanted a theme that looks like in screenshots in original theme's repository. Although those screenshots are somewhat outdated, I would rather keep `#222120`, it's more easy on the eyes.

What 'keywords' you are referring to?

**Comment by ghost** [comment]
I forgot to show the keywords in the screenshot, so there they are:
![badwolf-color-comparison](https://cloud.githubusercontent.com/assets/7250745/12374022/1f5f6ffc-bc8f-11e5-9c80-0db55e373ade.png)

Altering the colors is not hard, and if anyone prefers any other version, it would be easy to change.

It looks nice like that as well!

**Comment by bkruczyk** [comment]
As for keyword color in your screenshot I think it's just Emacs thing, the color hex for `taffy` is the same in Emacs as in Vim.

For darker background I'll probably could make an option like `badwolf-darker-background`. Will see.
