### ISSUE TITLE
Differences compared to Vim original

### ISSUE THREAD

**Issue by tinylucid** [bkruczyk/badwolf-emacs#7]
This was my absolutely favorite theme that I used during my Vim days. And I am glad to see it available on Emacs, so thanks for the hard work. But! Because I spend a lot of time in Vim with that theme I spotted some differences. As you can see in screenshot provided, different things are highlighted (for my taste, I like it with less colors like in Vim), exceptions are green in Vim, and comments are different. Did you notice this, and built this theme on purpose like this? 

<img width="720" alt="screen shot 2016-09-19 at 20 35 41" src="https://cloud.githubusercontent.com/assets/10340299/18644285/10cb0762-7ea9-11e6-8572-301444721227.png">
<img width="720" alt="screen shot 2016-09-19 at 20 36 03" src="https://cloud.githubusercontent.com/assets/10340299/18644808/09cd865e-7eab-11e6-9ede-2e3c8df9fbaf.png">

I hope you can see the differences, for example look at Exception and the green color, is it because of elpy and Emacs treat code differently than vim?

**Comment by bkruczyk** [comment]
Yeah I think I like Vim coloring better too, unfortunately that's how Emacs handles font locking (syntax coloring). If elpy does not define additonal faces for exception raising, Python class name (etc.) I'm afraid I can't do much about it.

As for docstrings it can be done easily, but I'm not sure if docstrings are colored in all prog languages with `dirtyblonde`, I'll check that.

**Comment by tinylucid** [comment]
Yup, looks like font locking is different with Emacs. It colors too many things for my taste. It would be hideous to go and edit by hand font locking for specific modes.
